# Moving the endpoint and credentials to a separate script
# so the env variables will override any bundled configurations
cf set-env $BROKER_APP_NAME SECURITY_USER_NAME $BROKER_USER_NAME
cf set-env $BROKER_APP_NAME SECURITY_USER_PASSWORD $BROKER_USER_PASSWORD
cf set-env $BROKER_APP_NAME CF_TARGET $CF_TARGET
cf set-env $BROKER_APP_NAME CF_ORG $INSTANCES_ORG
cf set-env $BROKER_APP_NAME CF_SPACE $INSTANCES_SPACE
cf set-env $BROKER_APP_NAME CF_USER $INSTANCES_SPACE_USER
cf set-env $BROKER_APP_NAME CF_PASSWORD $INSTANCES_SPACE_USER_PASSWORD
